### ISSUE TITLE
Love Babbar DSA 450 Sloutions

### ISSUE THREAD

**Issue by cryptus-neoxys** [skjha1/Competitive-Coding#2]
# Love Babbar DSA 450 [Array & String Question Sets]
Hey, I have been solving this sheet from Love Babbar and made some progress in the Arrays and String Sets.

I would like to contribute solutions to those problems.

## Arrays:
-  | 0 | Reverse the array
-  | 1 | Find the maximum and minimum element in an array
-  | 2 | Find the "Kth" max and min element of an array
-  | 3 | Given an array which consists of only 0, 1 and 2. Sort the array without using any sorting algo
-  | 4 | Move all the negative elements to one side of the array
-  | 5 | Find the Union and Intersection of the two sorted arrays.
-  | 6 | Write a program to cyclically rotate an array by one.
-  | 7 | find Largest sum contiguous Subarray [V. IMP]
-  | 9 | Minimum no. of Jumps to reach end of an array
-  | 10 | find duplicate in an array of N+1 Integers
-  | 12 | Kadane's Algo [V.V.V.V.V IMP]
-  | 13 | Merge Intervals

## Strings 

-  | 0 | Reverse a String
-  | 1 | Check whether a String is Palindrome or not
-  | 2 | Find Duplicate characters in a string
-  | 3 | Why strings are immutable in Java?

**Kindly assign this to me.** @skjha1

**Comment by skjha1** [comment]
Hello Dev! I appreciate what you did, but this repo is for further revision purposes I will be uploading my own codings.

thankyou @cryptus-neoxys.

**Comment by cryptus-neoxys** [comment]
> Hello Dev! I appreciate what you did, but this repo is for further revision purposes I will be uploading my own codings.
> 
> thankyou @cryptus-neoxys.
> 

No worries👍🏻
